### ISSUE TITLE
Legends not appearing in plot

### ISSUE THREAD

**Issue by dnjst** [earmingol/cell2cell#19]
Hello,

I am trying to reproduce the example notebook Tensor-cell2cell-PBMC.ipynb on my system, and everything works up until the step:

`c2c.plotting.tensor_factors_plot()`

at which point, the plot lacks any of the annotation legends and just shows the plots.

I'm using the latest matplotlib 3.6.2 in a jupyter notebook

Is this some sort of regression or version mismatch, or an error on my end? Apologies if this is my own fault.

![cell2cell_nolegend](https://user-images.githubusercontent.com/87722897/203169833-f170d080-fc37-4f1a-b221-6c02f153f2db.png)

**Comment by earmingol** [comment]
Hi!

Thanks for your question. Indeed there is some issues we have observed given the version of matplotlib.

I recommend using the version `3.2.0`, but that one is not available for all python versions. An option to that version is `3.5.1`.

I hope this helps! We will work on improving these compatibility issues in the future.
