### ISSUE TITLE
extract LR pairs in each factor

### ISSUE THREAD

**Issue by Wulin-Tan** [earmingol/cell2cell#22]
Hi, cell2cell team
cell2cell and tensor-cell2cell are amazing tools and can perfectly fit my project.
with the tutorial, I can construct the tensor and run the tensor-cell2cell pipeline.
But how can I extract all LR pairs in each specific factor?

Wulin

**Comment by earmingol** [comment]
Hi @Wulin-Tan

I recommend taking a look to this notebook, particularly to the last part: https://earmingol.github.io/cell2cell/tutorials/ASD/02-Factor-Specific-ASD/

If you want to prioritize top LR pairs per factor, you can change this parameter `loading_threshold`. If you want to include all LR pairs, just assign `loading_threshold=0.`

I hope this helps.

Erick
