### ISSUE TITLE
Elbow Rank 1?

### ISSUE THREAD

**Issue by inofechm** [earmingol/cell2cell#25]
Hi Erick,
Thank you for developing a great tool.
I am trying to run tensorcell2cell on an output from LIANA-py.
Whenever I try to automatically calculate the number of factors with the elbow analysis, I am getting a value of 1.
Its also weird because the error is increasing as we there are more factors...
Could you please advise if this is expected or whether there may be an issue with how I am using the package?
For reference I am looking at 26 samples representing 3 contexts, I am also using a gpu.
Thank you

Here is a screenshot of the figure:
![Screen Shot 2023-02-02 at 1 57 32 PM](https://user-images.githubusercontent.com/82839549/216423338-95a779b3-319d-4dd9-a744-bf19f2627e38.png)

My code is as follows:

`
#load dependencies
import cell2cell as c2c
import scanpy as sc
import numpy as np
import pandas as pd
from tqdm import tqdm
import matplotlib.pyplot as plt
import seaborn as sns
import os
import sys
args = sys.argv[1:]
folder_name = args[0]
use_gpu = args[1]
if use_gpu == 'True':
    use_gpu = True
else:
    use_gpu = False

output_folder =  folder_name

if use_gpu:
    import tensorly as tl
    tl.set_backend('pytorch')
    device = 'cuda'
else:
    import tensorly as tl
    tl.set_backend('pytorch')
    device = 'cpu'
#list files in results directory
files_liana_res = os.listdir("liana_py_res/")
#create list of dataframes
list_liana_files = []

for x in files_liana_res:
    list_liana_files.append(pd.read_csv("liana_py_res/" + x))

#convert list to dictionary
print('converting list to dictionary')
context_df_dict = dict(zip(files_liana_res, list_liana_files))
#build tensor
print('building tensor')

tensor_res = c2c.tensor.dataframes_to_tensor(context_df_dict = context_df_dict, sender_col = 'source', receiver_col = 'target',
 ligand_col = 'ligand_complex', receptor_col = 'receptor_complex', score_col = 'lrscore', how='outer', 
 outer_fraction=0.0, lr_sep='^', context_order=None, order_labels=None, sort_elements=True, device=device)

lr_pairs = pd.read_csv('lr_pairs.csv')
lr_pairs = lr_pairs.astype(str)
int_columns = ('source_genesymbol', 'target_genesymbol')

ppi_functions = dict()

for idx, row in lr_pairs.iterrows():
    ppi_label = row[int_columns[0]] + '^' + row[int_columns[1]]
    ppi_functions[ppi_label] = row['category_intercell_source']

context_dict = dict()

for sample in files_liana_res:
    if 'LUNG_T' in sample:
        context_dict[sample] = 'early stage tumour'
    elif 'LUNG_N' in sample:
        context_dict[sample] = 'normal tissue'
    elif 'EBUS' in sample:
        context_dict[sample] = 'late stage tumour'
    elif 'BRONCHO' in sample:
        context_dict[sample] = 'late stage tumour'

meta_tensor = c2c.tensor.generate_tensor_metadata(interaction_tensor=tensor_res,
                                                  metadata_dicts=[context_dict, ppi_functions, None, None],
                                                  fill_with_order_elements=True
                                                  )

elbow, error = tensor_res.elbow_rank_selection(upper_rank=30, 
                                           runs=20,
                                           init='svd',
                                           automatic_elbow=True,
                                           random_state=888,filename=output_folder + '/Elbow.svg'
                                          )
print(tensor_res.rank)`

**Comment by earmingol** [comment]
Hi Ido!

Thanks for submitting this issue. Just by looking at your plot, I would say that it could be due to the sparsity of the tensor and/or the number of masked values. If it is too high, that could be messing up the analysis. Could you check that with these commands?

```
tensor_res.sparsity_fraction()
```

```
tensor_res.missing_fraction()
```

Another option to deal with this could be running the elbow analysis based on the decomposition similarity instead, so you should use something like this:

```
elbow, error = tensor_res.elbow_rank_selection(upper_rank=30,
                                              runs=20,
                                              init='svd',
                                              automatic_elbow=True,
                                              metric='similarity', 
                                              smooth=True,
                                              random_state=888,filename=output_folder + '/Elbow.svg'
)
```

If this still does not work, another way to improve it could be by reducing the `expr_prop` when running LIANA, so you have less missing values.


I hope this helps

**Comment by inofechm** [comment]
Hi Erick Thanks for the quick reply!

I you were correct and it was the LIANA expr-prop. 
It worked as expected after setting expr_prop to 0!
Here's the new elbow plot
![Screen Shot 2023-02-03 at 9 02 33 AM](https://user-images.githubusercontent.com/82839549/216622690-8a2296a8-6672-465b-8191-d5d33dafab00.png)

**Comment by earmingol** [comment]
Glad to hear that it worked now! 

I recommend using a value different to zero for the LIANA parameter, maybe something `expr_prop=0.05` could be useful, so you make show to discard genes that are expressed by very few cells in a cluster. At the same time, if you use `expr_prop=0.05`in LIANA, I recommend building the tensor using `outer_fraction=0.25` or even higher values. In this way you have a better trade-off for prioritizing true positive signals.

**Comment by dbdimitrov** [comment]
Hi @inofechm,

This is now something covered by the `return_all_lrs` parameter. It essentially returns all interactions, following expr_thresh filtering.

I use it here when I run tensor:
https://liana-py.readthedocs.io/en/latest/notebooks/liana_c2c.html

**Comment by inofechm** [comment]
Cheers thanks for all the help Erick and Daniel!
I'm super excited to play with this combined workflow
