### ISSUE TITLE
Gene expression normalization

### ISSUE THREAD

**Issue by joan-yanqiong** [earmingol/cell2cell#27]
Hi, I want to use the tool with scRNAseq data. Is normalization needed? Or is UMI fine?

**Comment by earmingol** [comment]
Hi!

It depends on the aggregation method you use for summarizing the expression within a cluster. If you are using an aggregation of the fraction of cells expressing a gene, UMI is fine. However, if you plan to compute the average expression within a cell type, or any other, I recommend using log1p(CPM). The same applies for using distinct communication scores: if you are using continuous ones it's better using log1p(CPM). Also, it is important that your cell type annotation is done after batch-effect correction if you have multiple samples.

I hope this helps!

**Comment by joan-yanqiong** [comment]
Hi, thank you for the help!
