### ISSUE TITLE
IndexError at permutation step

### ISSUE THREAD

**Issue by joan-yanqiong** [earmingol/cell2cell#28]
Hi, I ran the jupyter notebook with the example workflow, which worked. So then I tried to use my own data, unfortunately I am running into a problem with the permutations. 

The data that i'm using is all in the same format as the example data and everything works fine until the permutation step. Please let me know if you need any specific information.

`100%|██████████| 2[/2](https://file+.vscode-resource.vscode-cdn.net/2) [01:47<00:00, 53.67s[/it](https://file+.vscode-resource.vscode-cdn.net/it)]
[/opt/homebrew/Caskroom/miniforge/base/envs/x86/lib/python3.7/site-packages/cell2cell/analysis/cell2cell_pipelines.py:767](https://file+.vscode-resource.vscode-cdn.net/opt/homebrew/Caskroom/miniforge/base/envs/x86/lib/python3.7/site-packages/cell2cell/analysis/cell2cell_pipelines.py:767): VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  randomized_scores = np.array(randomized_scores)
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
[/var/folders/6b/g_91_4015mq9blk_m03vj43h0000gn/T/ipykernel_24679/3288031412.py](https://file+.vscode-resource.vscode-cdn.net/var/folders/6b/g_91_4015mq9blk_m03vj43h0000gn/T/ipykernel_24679/3288031412.py) in 
     19                                              permutations=args.nperm,
     20                                              fdr_correction=True,
---> 21                                              verbose=True)

[/opt/homebrew/Caskroom/miniforge/base/envs/x86/lib/python3.7/site-packages/cell2cell/analysis/cell2cell_pipelines.py](https://file+.vscode-resource.vscode-cdn.net/opt/homebrew/Caskroom/miniforge/base/envs/x86/lib/python3.7/site-packages/cell2cell/analysis/cell2cell_pipelines.py) in permute_cell_labels(self, permutations, evaluation, fdr_correction, random_state, verbose)
    769         pvals = np.ones(base_scores.shape)
    770         for i in range(len(base_scores)):
--> 771             dist = randomized_scores[:, i]
    772             dist = np.append(dist, base_scores[i])
    773             pvals[i] = permutation.compute_pvalue_from_dist(obs_value=base_scores[i],

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed`

**Comment by earmingol** [comment]
Hi!

This seems like a bug when running 2 permutations... try increasing the number of permutations. I will try to implement a fix for this scenario soon.

**Comment by joan-yanqiong** [comment]
There is no attribute `interaction_element`. 
`---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
[/var/folders/6b/g_91_4015mq9blk_m03vj43h0000gn/T/ipykernel_47140/3994596067.py](https://file+.vscode-resource.vscode-cdn.net/var/folders/6b/g_91_4015mq9blk_m03vj43h0000gn/T/ipykernel_47140/3994596067.py) in 
----> 1 interactions.interaction_elements["communication_matrix"]

AttributeError: 'SingleCellInteractions' object has no attribute 'interaction_elements'`

**Comment by joan-yanqiong** [comment]
<img width="1340" alt="image" src="https://user-images.githubusercontent.com/43519278/226630979-28e6de53-5aae-46ff-b2eb-ad81741fab1a.png">

<img width="771" alt="image" src="https://user-images.githubusercontent.com/43519278/226631093-2f360e75-7bd8-486d-b35e-483b516befa4.png">

**Comment by earmingol** [comment]
Could you provide the code you are using for this? It looks like that in each permutation is generating a result of different length, so something is probably wrong with the setups or single-cell metadata.

I just pushed a potential fix, but if the permutations are generating varying length outputs the fix may still run but generating wrong results.

**Comment by joan-yanqiong** [comment]
Hope that this provides the information you need. 

[cci_cell2cell.pdf](https://github.com/earmingol/cell2cell/files/11042764/cci_cell2cell.pdf)

**Comment by earmingol** [comment]
Thanks!

Just by looking your code, I would try the following:
- Avoid doing this rename: `rnaseq.index.name = "index"`, just use it for the columns (single cells). That means, only keep this `rnaseq = rnaseq.rename_axis("index", axis=1)` and remove `rnaseq.index.name = "index"`.
- Load your data with scanpy to directly use a AnnData object instead. E.g. `adata = scanpy.read_10x_mtx()` and assign the metadata after loading it in this way: `adata.obs = meta.copy()`
- Try using a different communication score (e.g. `communication_score="expression_gmean"`). If you do that, I recommend using `aggregation_method='average'`. In this case your data should be preprocessed to be log1p(CPM).
- If nothing of that works, try updating to the new version of cell2cell (`pip install -U cell2cell`). I would keep this as the last thing to try since I am not 100% sure that the fix I included will solve your issue properly (it may output things, but probably something is going wrong in the way you are passing the data).

Also, how many LR pairs are in your DB? 4,587?

I hope that any of these options solves your issue!

**Comment by joan-yanqiong** [comment]
I just figured out what the problem was. My gene expression dataframe was a subset of my total dataset, though my metadata corresponded to the total dataset. In other words, the number of cells was different. So now I filtered the metadata and it seems to work. 

Thanks for your fast responses and help!
