### ISSUE TITLE
predicting on new data

### ISSUE THREAD

**Issue by Katan5555** [earmingol/cell2cell#29]
Hello,
Thanks for developing this great tool.  Do you have an example of how to stratify patients with the learnt factors ? from one dataset (training) to another (testing), and by identifying the same factor in both dataset. I guess we would have to compared the loadings at all 4 levels.

Thanks !

**Comment by earmingol** [comment]
This is something that in tensor decomposition is different to PCA for example. Usually the decomposition is performed in the whole dataset at a time. However, from the tensorly repo it looks like that something like this is possible. If you have an initial model (training data), you can add more samples as long as the testing tensor contains exactly the same elements and order for the other dimensions (LR pairs, sender cells, and receiver cells). Here there is more discussion about this: https://github.com/tensorly/tensorly/issues/386

Nevertheless, this is something he haven't tried yet. Eventually we will provide more guidelines for doing so.

**Comment by Katan5555** [comment]
Thanks  a lot for your reply ! I'll check it out. 

On a slightly different topic but nevertheless related: 

1) Sometimes, we don't always see that much difference between 2 contexts (case vs control) especially when having more samples. Of course, we can do a group comparison of factor loading (like the boxplots), but this still doesn't always work. One thing I tried is to group all samples in case as 1 sample and all controls as a second sample. It's like running tensor on 2 samples: case and control. And this is when I can see a huge difference sometimes of case vs control. What do you think of this strategy ? 

2) Suppose we're seeing a difference between case vs control at a certain factor. Don't you think that having **how='outer'** makes more sense than **how='inner'** in **c2c.tensor.InteractionTensor** function ? If we're interested in factor that captures the specificity of **case** situation, why would we expect receptor ligand interaction that appears in **control** ?

**Comment by earmingol** [comment]
You are welcome! :)

Regarding your questions:
1. Yes, aggregating separate samples into groups it something that can be done, especially when you there are missing values per samples. This aggregation helps to complete those missing values. If you do not need to compare the communication in a sample-specific way then doing this makes sense. However, if you need statitistical power, it's better using samples separately because with this you can perform statistical tests with N's distinct to 1.
2. If you want to identify attributes that are case specific, using outer makes sense since the decomposition should prioritize that when having missing values (i.e. communication present in specific samples). We added more detailes about controling the parameter `how` and the way you can be flexible or more strict by controling the `outer_fraction` to consider cases that are present in a given fraction of samples. You can find more info about it here: https://ccc-protocols.readthedocs.io/en/latest/notebooks/ccc_python/03-Generate-Tensor.html#Supplementary-Information-about-Tensor-cell2cell

**Comment by Katan5555** [comment]
Let's consider an example of 10 patients. 5 controls (wild type gene X) and 5 cases (mutation gene X). 
After running tensor cell2cell, we find that factor 5 captures the mutated gene X (much higher loading in case vs control). Then we also find that in Factor 5, the top 3 sending cells are: B, T, DC. And the top 3 receiver cells are Macrophage, T and NK. And the top receptor ligand pair is gene A - gene B. 

What can we actually conclude ? According to tensor factorization, it just means for the samples where gene X is mutated, the top sending/receiving cells and R/L are what they are. And but doing an outer product of context/sender/receiver/R/L interaction we get the full 4D tensor. But we still don't know where gene A and B are expressed. They could be expressed on B and Macrophage, but we don't know that for sure.

**Comment by Katan5555** [comment]
Hi Erick,

I am getting so many different results based on the* random_state* number
here:

tensor.compute_tensor_factorization(rank=tensor.rank ,
init='svd',
random_state=9
)

I am starting to get really worried. If we can produce so many models and
so different, which one can I trust ?
Do you have a way to decide about the best model ? I also wonder whether
this random_state should be the same as in tensor.elbow_rank_selection

Thanks !

Mi

**Comment by Katan5555** [comment]
I think I might know the problem. I have set the patient labels as "case"
and "control", so only 2 patients in the end. And things become very
unstable when there is an imbalance. One group has much more cells than the
other. Could this be why the result depends so much on the seed number ?

**Comment by earmingol** [comment]
Hi! sorry the delay,

Regarding the meaning of your factor, to associated high expression of the ligands in the top LR pairs by the sender cells, and the same for the receptors by the receiver cells, you have to make sure that the communication score you are using reflects that. One case to use could be 'expression_gmean' after aggregating expression to be the average of the log1p(CPM) values. 

I recommend not only observing the top-1 LR pair, also consider multiple top cases and use a downstream analysis to associate functions (see https://ccc-protocols.readthedocs.io/en/latest/notebooks/ccc_python/05-Downstream-Visualizations.html and https://ccc-protocols.readthedocs.io/en/latest/notebooks/ccc_python/06-Functional-Footprinting.html)

Regarding the unstable results coming from different seeds, unfortunately this could happen with tensor decomposition algorithms. See this previous response for more information about that behavior and how to measure the similarity of results when varying the seeds:  https://github.com/earmingol/cell2cell/issues/13#issuecomment-1261367337

A good way to deal with this is running the decomposition multiple times and selecting the one with lowest error. This is a "robust" way to run the decomposition and avoid unstability of the results: 

```
tensor.compute_tensor_factorization(rank=tensor.rank,
                                                               init='random',
                                                               random_state=888, # Replace by any seed
                                                               runs=100,
                                                               normalize_loadings=True,
                                                               tol=1e-8, n_iter_max=500,
                                                               )
```

If this does not work, a potential issue could be the sparsity of your tensor when using any case of `how='outer'` or variations. You can check that with: `tensor.excluded_value_fraction()`

Sometimes you can get different results when varying the random_state, but it does not mean that they are different at all. They may have some variations in the loadings, bu the overall behavior would represent the same. Also this kind of tensor decomposition allows permutations of the factors, and for example with a seed, your factor 1 could be another factor with another seed.

To check the similarity of your multiple runs, I recommend running and elbow analysis but with the similarty metric, so you will know that even though you get different decomposition results, they still represent similar behaviors:

```
tensor.elbow_rank_selection(upper_rank=25,
                                           runs=10,
                                           init='svd',
                                           metric='similarity',
                                           automatic_elbow=True,
                                           random_state=888, # Replace by any seed
                                          )
```

If you get a weird curve, you can smooth it by adding the parameter `smooth=True`

**Comment by Katan5555** [comment]
Hi Erick,

Thanks a lot for your reply ! It all works out. But I just realize, having
a more stable result is not always the best. For ex, using the previous
method, I could have for a certain factor, one context much higher loading
than the other, and looking at the corresponding L/R pair it all makes
sense: I divided the dataset in 2 parts, context + and context -, run LIANA
in each, and I see that the L/R pair selected was indeed important.

But now that I use the more stable code, I don't find any factor with
context + much higher than context -. and the new L/R pairs are of course
not supported by independent analysis with LIANA.

Best,

Mi
