### ISSUE TITLE
Linking the single cell tutorial with new vertsion of cell2cell

### ISSUE THREAD

**Issue by Sophon-0** [earmingol/cell2cell#30]
Hello, 
I would like to know if it's possible to do some interaction heatmap plot and PCoA Euclidean space  plot with the new tutorial on ASD with Factor map. I tried to do some interaction plots with my own data, but I don't think the format and parameters are the same.
Thanks !

**Comment by earmingol** [comment]
Hi!

Thanks for pointing this out! The single cell tutorials are mostly for the regular cell2cell tool, while the ASD are intended for Tensor-cell2cell, that is why they are not consistent in the data and examples they have. However, we will redo these tutorial for having more consistency.

Regarding the PCoA plot, this is intended to be run on overall CCI scores, which could be potentially integrated with the factor-specific networks built from Tensor-cell2cell. If this helps, we are currently working on some tutorials integrating LIANA (computing the cell-cell communication scores) and Tensor-cell2cell (extracting context-driven programs from the CCC scores), available here and soon in a protocol manuscript: https://ccc-protocols.readthedocs.io/ 
However we do not use anything here like in the single-cell tutorial for cell2cell (which could be equivalent to running LIANA for the CCC scores).
