### ISSUE TITLE
Liana_tensor_c2c: Error setting up conda environment with Basilisk, no module named scipy

### ISSUE THREAD

**Issue by reneemoerkens** [earmingol/cell2cell#35]
Hello,

I am not sure whether I should post this error here or on the Basilisk Github page, so please feel free to let me know.

I am running the Liana x tensor cell2cell tutorial from R and I get this error message: 

Code:
````
sce <- liana_tensor_c2c(sce = sce,
                        score_col = 'LRscore',
                        rank = NULL,  # set to None to estimate for you data!
                        how='outer',  #  defines how the tensor is built
                        conda_env = NULL, # used to pass an existing conda env with cell2cell
                        use_available = FALSE # detect & load cell2cell if available
)
````

Error message:
```
Setting up Conda Environment with Basilisk
Error : ModuleNotFoundError: No module named 'scipy'

Error in .activate_fallback(proc, testload, env = env, envpath = envpath) : 
  ModuleNotFoundError: No module named 'scipy'
```

So far I couldn't resolve it. I am using Basilisk version 1.13.1 and Reticulate 1.28.
Perhaps you could help me troubleshoot?

Thanks!

**Comment by dbdimitrov** [comment]
Hey @reneemoerkens,

It seems that perhaps the (automatic) environment was not set up properly, as scipy is one of the main libraries.
You could instead set it up manually and pass it's name to the `conda_env` parameter. As we do in this repo: https://github.com/saezlab/ccc_protocols, and more specifically this tutorial: https://ccc-protocols.readthedocs.io/en/latest/notebooks/ccc_R/QuickStart.html

Let me know if this helps :)

You could also find the conda environment called `liana_cell2cell` and delete it, then the automatic setup that `liana` initiates in the background will start from scratch.

**Comment by reneemoerkens** [comment]
Hey @dbdimitrov,

Thank you for the suggestion! I will try delete the environment first and if that doesn't work I will set-up manually.
