### ISSUE TITLE
Spatial LIANA x cell2cell analysis in R

### ISSUE THREAD

**Issue by Qirongmao97** [earmingol/cell2cell#51]
Thank you for developing the cell2cell pipeline.

I am curious whether it's possible to perform spatial transcriptomics analysis using LIANA x cell2cell in R, given the challenges of interoperability between Python and R for spatial data.

**Comment by dbdimitrov** [comment]
Hi @Qirongmao97,

What type of spatial experiment would you like to analyse? 

Note that the default approach to combine liana and tensor requires cell clusters. So, your application might depend a lot on the dataset in mind.

Daniel

**Comment by Qirongmao97** [comment]
Hi Daniel,

Thanks for the quick response :)

We have Visium data in different groups, and we also have the clustering annotation for different spots.
