### ISSUE TITLE
can't run bash -i setup_env.sh --conda --gpu --kernel (python 3.10); the env is incompatible in python 3.7 when installing liana-py liana-R pytorch cell2cell togather

### ISSUE THREAD

**Issue by huiyijiangling** [earmingol/cell2cell#60]
![image](https://github.com/user-attachments/assets/2e95d202-5868-46d7-bcd9-a03a2f734c8a)

Hope to use your wonderful packages. I tested the installtion on wsl, win10,  and ubuntu but failed.

**Comment by huiyijiangling** [comment]
https://ccc-protocols.readthedocs.io/en/latest/notebooks/ccc_R/QuickStart.html#
![image](https://github.com/user-attachments/assets/19cf1b2f-d1b7-47db-a075-de8d1b3cda2e)

**Comment by earmingol** [comment]
closing this since a reply has been provided here: https://github.com/saezlab/ccc_protocols/issues/17#issuecomment-2269285591
